In [2]:
#Traffic analysis 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
from datetime import datetime, timedelta
import warnings

In [3]:
df = pd.read_excel('/Users/thomas/Data/Dynamic_weight_data/Marzo/1 marzo - 7 marzo/2.xlsx')
df.head()

,Id,StartTime,StartTimeStr,LaneNo,LaneName,BaseClassId,Scheme,ClassId,MoveStatus,FrontToFront,...,WheelBase,FrontOverhang,AxlesCount,MassUnit,VelocityUnit,DistanceUnit,WheelType,StrongAcceleration,StrongDeceleration,DateTimeTransit
0,738780,1741220000000,2025-06-03 00:16:00,2,Corsia 1 - Marcia,19,EUR13,12,-1,263.822,...,6.09,1.13,2,kg,km/h,m,D,0,0,2025-06-03 00:16:00
1,738860,1741220000000,2025-06-03 01:31:00,3,Corsia 2 - Marcia veloce,21,EUR13,1,1,188.386,...,2.80,0.39,2,kg,km/h,m,N,0,0,2025-06-03 01:31:00
2,738906,1741230000000,2025-06-03 02:19:00,2,Corsia 1 - Marcia,15,EUR13,9,-1,394.219,...,11.81,1.14,5,kg,km/h,m,D,0,0,2025-06-03 02:19:00
3,759360,1741310000000,2025-07-03 00:08:00,2,Corsia 1 - Marcia,15,EUR13,9,-1,398.533,...,11.60,1.43,5,kg,km/h,m,D,0,0,2025-07-03 00:08:00
4,759382,1741310000000,2025-07-03 00:32:00,3,Corsia 2 - Marcia veloce,21,EUR13,1,-1,344.737,...,2.92,0.16,2,kg,km/h,m,N,0,0,2025-07-03 00:32:00

In [4]:
df.describe()

,Id,StartTime,StartTimeStr,LaneNo,BaseClassId,ClassId,MoveStatus,FrontToFront,BackToFront,Duration,...,GrossWeight,LeftWeight,RightWeight,Velocity,WheelBase,FrontOverhang,AxlesCount,StrongAcceleration,StrongDeceleration,DateTimeTransit
count,68798.000000,6.879800e+04,68798,68798.000000,68798.000000,68798.00000,68798.000000,68798.000000,68798.000000,68798.000000,...,68798.000000,68798.000000,68798.000000,68798.000000,68798.00000,68798.000000,68798.000000,68798.000000,68798.000000,68798
mean,769335.562545,1.741347e+12,2025-07-01 09:39:11.481438464,2.864575,19.541106,2.57570,0.014099,10.533541,10.292911,0.401591,...,5521.737405,2810.357132,2711.380273,121.789994,4.03284,0.555056,2.377671,0.000073,0.000087,2025-07-01 09:39:11.481438464
min,734729.000000,1.741190e+12,2025-05-03 16:44:00,2.000000,1.000000,1.00000,-1.000000,-6.409000,-6.565000,0.125000,...,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,1.000000,0.000000,0.000000,2025-05-03 16:44:00
25%,752041.250000,1.741270e+12,2025-06-03 14:21:00,2.000000,21.000000,1.00000,-1.000000,2.500000,2.260000,0.250000,...,1410.000000,740.000000,650.000000,108.000000,2.58000,0.180000,2.000000,0.000000,0.000000,2025-06-03 14:21:00
50%,769354.500000,1.741350e+12,2025-07-03 12:01:00,3.000000,21.000000,1.00000,0.000000,5.277000,5.036000,0.288000,...,1700.000000,910.000000,810.000000,124.000000,2.69000,0.360000,2.000000,0.000000,0.000000,2025-07-03 12:01:00
75%,786639.750000,1.741430e+12,2025-08-03 10:59:00,3.000000,21.000000,1.00000,1.000000,10.672000,10.396000,0.371000,...,2390.000000,1290.000000,1230.000000,136.000000,3.01000,0.580000,2.000000,0.000000,0.000000,2025-08-03 10:59:00
max,803880.000000,1.741470e+12,2025-08-03 22:59:00,4.000000,24.000000,13.00000,1.000000,3429.760000,3429.560000,151.125000,...,64660.000000,34170.000000,32550.000000,357.000000,18.39000,4267.420000,8.000000,1.000000,1.000000,2025-08-03 22:59:00
std,19967.853725,8.258903e+07,NaN,0.696072,3.997269,3.32707,0.926852,29.570614,29.564973,0.864308,...,9799.628883,4936.587153,4878.856738,23.125029,3.22368,17.855901,0.960747,0.008525,0.009338,NaN

In [5]:
df.columns

Index(['Id', 'StartTime', 'StartTimeStr', 'LaneNo', 'LaneName', 'BaseClassId',
       'Scheme', 'ClassId', 'MoveStatus', 'FrontToFront', 'BackToFront',
       'Duration', 'VehicleLength', 'GrossWeight', 'LeftWeight', 'RightWeight',
       'Velocity', 'WheelBase', 'FrontOverhang', 'AxlesCount', 'MassUnit',
       'VelocityUnit', 'DistanceUnit', 'WheelType', 'StrongAcceleration',
       'StrongDeceleration', 'DateTimeTransit'],
      dtype='object')

In [6]:
df['ClassId'].unique()

array([12,  1,  9,  8,  2, 13,  5,  3,  6, 10,  4,  7, 11])

In [7]:
df.groupby(by='ClassId').count()

,Id,StartTime,StartTimeStr,LaneNo,LaneName,BaseClassId,Scheme,MoveStatus,FrontToFront,BackToFront,...,WheelBase,FrontOverhang,AxlesCount,MassUnit,VelocityUnit,DistanceUnit,WheelType,StrongAcceleration,StrongDeceleration,DateTimeTransit
ClassId,,,,,,,,,,,,,,,,,,,,,
1,52479,52479,52479,52479,52479,52479,52479,52479,52479,52479,...,52479,52479,52479,52479,52479,52479,52479,52479,52479,52479
2,3801,3801,3801,3801,3801,3801,3801,3801,3801,3801,...,3801,3801,3801,3801,3801,3801,3801,3801,3801,3801
3,277,277,277,277,277,277,277,277,277,277,...,277,277,277,277,277,277,277,277,277,277
4,78,78,78,78,78,78,78,78,78,78,...,78,78,78,78,78,78,78,78,78,78
5,201,201,201,201,201,201,201,201,201,201,...,201,201,201,201,201,201,201,201,201,201
6,220,220,220,220,220,220,220,220,220,220,...,220,220,220,220,220,220,220,220,220,220
7,137,137,137,137,137,137,137,137,137,137,...,137,137,137,137,137,137,137,137,137,137
8,2186,2186,2186,2186,2186,2186,2186,2186,2186,2186,...,2186,2186,2186,2186,2186,2186,2186,2186,2186,2186
9,6280,6280,6280,6280,6280,6280,6280,6280,6280,6280,...,6280,6280,6280,6280,6280,6280,6280,6280,6280,6280
10,130,130,130,130,130,130,130,130,130,130,...,130,130,130,130,130,130,130,130,130,130
11,13,13,13,13,13,13,13,13,13,13,...,13,13,13,13,13,13,13,13,13,13
12,1704,1704,1704,1704,1704,1704,1704,1704,1704,1704,...,1704,1704,1704,1704,1704,1704,1704,1704,1704,1704
13,1292,1292,1292,1292,1292,1292,1292,1292,1292,1292,...,1292,1292,1292,1292,1292,1292,1292,1292,1292,1292

In [ ]:
df = df[df['ClassId'] == 1]

df.groupby(by='ClassId').count()

In [8]:
df.tail()

,Id,StartTime,StartTimeStr,LaneNo,LaneName,BaseClassId,Scheme,ClassId,MoveStatus,FrontToFront,...,WheelBase,FrontOverhang,AxlesCount,MassUnit,VelocityUnit,DistanceUnit,WheelType,StrongAcceleration,StrongDeceleration,DateTimeTransit
68793,803875,1741470000000,2025-08-03 22:58:00,2,Corsia 1 - Marcia,21,EUR13,1,1,28.449,...,2.50,0.01,2,kg,km/h,m,N,0,0,2025-08-03 22:58:00
68794,803876,1741470000000,2025-08-03 22:59:00,2,Corsia 1 - Marcia,1,EUR13,13,0,19.504,...,2.44,0.05,2,kg,km/h,m,N,0,0,2025-08-03 22:59:00
68795,803877,1741470000000,2025-08-03 22:59:00,2,Corsia 1 - Marcia,21,EUR13,1,1,31.325,...,2.59,0.20,2,kg,km/h,m,S,0,0,2025-08-03 22:59:00
68796,803878,1741470000000,2025-08-03 22:59:00,3,Corsia 2 - Marcia veloce,21,EUR13,1,-1,19.399,...,2.46,0.21,2,kg,km/h,m,N,0,0,2025-08-03 22:59:00
68797,803880,1741470000000,2025-08-03 22:59:00,3,Corsia 2 - Marcia veloce,21,EUR13,1,-1,16.106,...,2.67,0.44,2,kg,km/h,m,N,0,0,2025-08-03 22:59:00

In [21]:
df.memory_usage()

Index                    132
Id                    550384
StartTime             550384
StartTimeStr          550384
LaneNo                550384
LaneName              550384
BaseClassId           550384
Scheme                550384
ClassId               550384
MoveStatus            550384
FrontToFront          550384
BackToFront           550384
Duration              550384
VehicleLength         550384
GrossWeight           550384
LeftWeight            550384
RightWeight           550384
Velocity              550384
WheelBase             550384
FrontOverhang         550384
AxlesCount            550384
MassUnit              550384
VelocityUnit          550384
DistanceUnit          550384
WheelType             550384
StrongAcceleration    550384
StrongDeceleration    550384
DateTimeTransit       550384
dtype: int64

In [ ]:
df['momentum'] = df['GrossWeight'] * df['Velocity']
df.head()
df.tail()
df.memory_usage()
df.describe()
df.columns
df.groupby(by='ClassId').count()